apiVersion: api.core.appnet.io/v1
kind: AppNetConfig
metadata:
  name: sample-echo-sidecar # Name of the AppNetConfig
spec:
  backend: sidecar # Name of the backend (sidecar/ambient/grpc)
  appName: echo # Name of the application
  clientService: frontend # Name of the client service (must be a valid service in the same namespace as the AppNetConfig)
  serverService: server # Name of the server service (must be a valid service in the same namespace as the AppNetConfig)
  method: echo # Name of the RPC method (defined in the proto file)
  appManifestFile: <APPNET_DIR_PATH>/config/samples/echo-stream/echo-stream.yaml # Path to the application manifest file
  clientChain:
    - name: nul # Name of the first element in the client chain
      file: <APPNET_DIR_PATH>/appnet/config/samples/echo-stream/null.appnet # Path to the fault injection element file
  proto: <APPNET_DIR_PATH>/appnet/config/samples/echo-stream/echo.proto # Path to the protobuf definition of client service to server service communication