apiVersion: api.core.adn.io/v1
kind: Adnconfig
metadata:
  name: sample-echo
spec:
  appName: echo
  clientService: frontend
  serverService: server
  method: echo
  appManifestFile: /users/xzhu/adn-controller/config/samples/echo/echo.yaml
  clientChain:
    - name: fault
      file: /users/xzhu/adn-controller/config/samples/echo/fault.adn
      parameters:
        probability: "0.02"
    - name: logging
      file: /users/xzhu/adn-controller/config/samples/echo/logging.adn
  serverChain:
    - name: acl
      file: /users/xzhu/adn-controller/config/samples/echo/acl.adn
      parameters:
        body: apple
  anyChain:
    - name: metrics
      file: /users/xzhu/adn-controller/config/samples/echo/metrics.adn
  proto: /users/xzhu/adn-controller/config/samples/echo/echo.proto
