---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - api.core.appnet.io
  resources:
  - appnetconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.core.appnet.io
  resources:
  - appnetconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - api.core.appnet.io
  resources:
  - appnetconfigs/status
  verbs:
  - get
  - patch
  - update
