apiVersion: api.core.appnet.io/v1
kind: AppNetConfig
metadata:
  name: sample-hotel
spec:
  appName: hotel
  clientService: frontend
  serverService: reservation
  method: MakeReservation
  appManifestFile: <APPNET_DIR_PATH>/compiler/examples/applications/hotel_reservation/hotel_reservation.yaml
  clientChain:
    - name: fault
      file: <APPNET_DIR_PATH>/compiler/examples/elements/reservation_elements/fault.adn
      parameters:
        probability: "0.02"
    - name: logging
      file: <APPNET_DIR_PATH>/compiler/examples/elements/reservation_elements/logging.adn
  serverChain:
    - name: acl
      file: <APPNET_DIR_PATH>/compiler/examples/elements/reservation_elements/acl.adn
      parameters:
        body: apple
  anyChain:
    - name: metrics
      file: <APPNET_DIR_PATH>/compiler/examples/elements/reservation_elements/metrics.adn
  proto: <APPNET_DIR_PATH>/compiler/examples/proto/reservation.proto
